apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-api
  namespace: task-manager
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - host: tasks.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: task-api
                port:
                  number: 80
